// Functional smoke test of the main flows in demo mode.
import { chromium } from 'playwright'
import fs from 'node:fs'

const base = process.argv[2] || 'http://127.0.0.1:4173'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const context = await browser.newContext({ viewport: { width: 1280, height: 860 } })
await context.addInitScript(() => { localStorage.setItem('hub-demo-user', 'u-russel'); if (!sessionStorage.getItem('flows-init')) { localStorage.removeItem('hub-demo-state-v2'); sessionStorage.setItem('flows-init', '1') } localStorage.setItem('hub-theme', 'light') })
const page = await context.newPage()
const errors = []
page.on('pageerror', (e) => errors.push('PAGEERROR ' + e.message))
page.on('console', (m) => { if (m.type() === 'error' && !/TUNNEL|favicon/.test(m.text())) errors.push(m.text()) })
fs.mkdirSync('qa-shots/flows', { recursive: true })
const shot = (n) => page.screenshot({ path: `qa-shots/flows/${n}.png` })

let failed = 0
const step = async (name, fn) => {
  try { await fn(); console.log('✓', name) } catch (e) { failed++; console.log('✗', name, e.message.split('\n')[0]); await shot(`fail-${name.replace(/\W+/g, '-')}`) }
}

await step('create project', async () => {
  await page.goto(base + '/projects/new', { waitUntil: 'networkidle' })
  await page.getByPlaceholder('e.g. Kitchen cabinet refresh').fill('Patio pergola')
  await page.getByPlaceholder('Repaint the carcasses, new shaker doors, brass handles…').fill('A timber pergola over the braai area.')
  await page.getByPlaceholder('0').first().fill('22000')
  await page.getByRole('button', { name: 'Start the quest' }).click()
  await page.waitForURL(/\/projects\/(?!new)/, { timeout: 10000 })
  await page.waitForTimeout(800)
  await shot('01-project-created')
  const xp = await page.locator('text=+25 XP').count()
  if (!xp) throw new Error('no XP pop')
})

await step('add + complete task', async () => {
  await page.getByRole('tab', { name: /^Tasks/ }).click()
  await page.getByLabel('New task').fill('Order timber')
  await page.getByRole('button', { name: 'Add' }).click()
  await page.waitForTimeout(400)
  await page.getByRole('checkbox', { name: 'Order timber' }).click()
  await page.waitForTimeout(600)
  await shot('02-task-done')
  const t = await page.locator('text=+10 XP').count()
  if (!t) throw new Error('no task XP')
})

await step('nudge Kay from the project', async () => {
  await page.getByRole('button', { name: 'Nudge Kay' }).first().click()
  await page.waitForTimeout(400)
  await page.getByRole('button', { name: 'Have a look at the board' }).click()
  await page.getByRole('button', { name: 'Send nudge' }).click()
  await page.waitForTimeout(600)
  await shot('02b-nudge')
  const t = await page.locator('text=Nudge sent to Kay').count()
  if (!t) throw new Error('no nudge toast')
})

await step('file quote + accept (with contact search)', async () => {
  await page.getByRole('tab', { name: /^Money/ }).click()
  await page.getByRole('button', { name: 'File a quote' }).click()
  await page.getByPlaceholder('Doors, paint & handles').fill('Pergola timber + build')
  await page.getByRole('button', { name: 'Supplier or contractor' }).click()
  await page.getByLabel('Search contacts').fill('joinery')
  await page.waitForTimeout(200)
  await page.getByRole('option', { name: /Joe Mahlangu/ }).click()
  await page.waitForTimeout(300)
  const picked = await page.locator('text=Joe Mahlangu · Joe\'s Joinery').count()
  if (!picked) throw new Error('contact not picked')
  await page.getByPlaceholder('0').first().fill('18500')
  await page.locator('select').filter({ hasText: 'Received' }).first().selectOption('accepted')
  await page.getByRole('button', { name: 'File quote' }).click()
  await page.waitForTimeout(800)
  await shot('03-quote')
  const q = await page.locator('text=Pergola timber + build').count()
  if (!q) throw new Error('quote missing')
})

await step('deposit on the accepted quote, then settle it', async () => {
  await page.getByRole('button', { name: 'Record a deposit' }).first().click()
  await page.waitForTimeout(400)
  await page.getByRole('button', { name: /^30% ·/ }).click()
  await page.getByRole('button', { name: 'Record payment' }).click()
  await page.waitForTimeout(800)
  await shot('03b-deposit')
  const partial = await page.locator('text=R 5 550 paid · R 12 950 to go').count()
  if (!partial) throw new Error('deposit not reflected on the quote')
  const inExpenses = await page.locator('text=Deposit — Pergola timber + build (30%)').count()
  if (!inExpenses) throw new Error('deposit missing from expenses')
  await page.getByRole('button', { name: 'Record another payment' }).first().click()
  await page.waitForTimeout(400)
  await page.getByRole('button', { name: /^Balance ·/ }).click()
  await page.getByRole('button', { name: 'Record & mark paid' }).click()
  await page.waitForTimeout(900)
  await shot('03c-settled')
  const full = await page.locator('text=Paid in full').count()
  if (!full) throw new Error('quote not settled')
})

await step('log expense', async () => {
  await page.getByRole('button', { name: 'Log' }).click()
  await page.getByPlaceholder('Soft-close hinges ×24').fill('Coach bolts')
  await page.getByPlaceholder('0').first().fill('340')
  await page.getByRole('button', { name: 'Log it' }).click()
  await page.waitForTimeout(600)
  const e = await page.locator('text=Coach bolts').count()
  if (!e) throw new Error('expense missing')
})

await step('board: add note, colour, drag', async () => {
  await page.getByRole('tab', { name: /^Board/ }).click()
  await page.getByRole('button', { name: 'Open board' }).click()
  await page.waitForURL(/\/board$/)
  await page.waitForTimeout(600)
  await page.getByRole('button', { name: 'Note' }).click()
  await page.getByPlaceholder('Handles: brushed brass, 160mm centres…').fill('Stain: dark walnut')
  await page.getByRole('button', { name: 'Pin it' }).click()
  await page.waitForTimeout(500)
  await page.getByRole('button', { name: 'Done' }).click()
  await page.getByRole('button', { name: 'Colour' }).click()
  await page.getByPlaceholder('#7A8F6E').fill('#5A4635')
  await page.getByRole('button', { name: 'Pin it' }).click()
  await page.waitForTimeout(500)
  await page.getByRole('button', { name: 'Done' }).click()
  await page.getByRole('button', { name: 'Label' }).click()
  await page.getByPlaceholder('Wall run 3.6 m').fill('Span 4.5 m')
  await page.getByRole('button', { name: 'Pin it' }).click()
  await page.waitForTimeout(500)
  await page.getByRole('button', { name: 'Done' }).click()
  await page.waitForTimeout(300)
  // drag the note
  const note = page.locator('text=Stain: dark walnut').first()
  const box = await note.boundingBox()
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + 200, box.y + 120, { steps: 12 })
  await page.mouse.up()
  await page.waitForTimeout(500)
  await shot('04-board')
  const b2 = await note.boundingBox()
  if (Math.abs(b2.x - box.x) < 50) throw new Error('note did not move')
  // reload and confirm persisted
  await page.reload({ waitUntil: 'networkidle' })
  await page.waitForTimeout(800)
  const n = await page.locator('text=Stain: dark walnut').count()
  if (!n) throw new Error('note not persisted')
})

await step('board: open a link pin', async () => {
  await page.goto(base + '/projects/p-kitchen/board', { waitUntil: 'networkidle' })
  await page.waitForTimeout(900)
  // Record where the app would send the browser, rather than actually opening pinterest.com.
  await page.evaluate(() => { window.__opened = []; window.open = (u) => { window.__opened.push(u); return { closed: false, focus() {} } } })
  const opened = () => page.evaluate(() => window.__opened)

  // the arrow button on the pin itself
  await page.getByRole('button', { name: /^Open pinterest\.com$/ }).click()
  await page.waitForTimeout(200)
  let urls = await opened()
  if (urls.length !== 1 || !/pinterest\.com/.test(urls[0])) throw new Error(`icon opened ${JSON.stringify(urls)}`)

  // tapping the pin selects it (rather than navigating) and offers a big Open button
  await page.locator('text=Sage shaker kitchens').first().click()
  await page.waitForTimeout(400)
  await shot('04b-link-selected')
  await page.getByRole('button', { name: 'Open link', exact: true }).click()
  await page.waitForTimeout(200)
  urls = await opened()
  if (urls.length !== 2 || !/pinterest\.com/.test(urls[1])) throw new Error(`pill opened ${JSON.stringify(urls)}`)

  // and the same action from the selected-pin toolbar
  await page.getByRole('button', { name: 'Open the link' }).click()
  await page.waitForTimeout(200)
  urls = await opened()
  if (urls.length !== 3) throw new Error(`toolbar opened ${JSON.stringify(urls)}`)

  // opening must not have navigated the board away
  if (!/\/board$/.test(page.url())) throw new Error('board navigated away: ' + page.url())

  // ...and the arrow still works straight after dragging a pin (a stale "that was a drag" flag used to eat the click)
  const pin = page.locator('text=Sage shaker kitchens').first()
  const box = await pin.boundingBox()
  await page.mouse.move(box.x + 40, box.y + box.height / 2)
  await page.mouse.down()
  await page.mouse.move(box.x + 40 + 70, box.y + box.height / 2 + 50, { steps: 10 })
  await page.mouse.up()
  await page.waitForTimeout(400)
  await page.getByRole('button', { name: /^Open pinterest\.com$/ }).click()
  await page.waitForTimeout(200)
  urls = await opened()
  if (urls.length !== 4) throw new Error(`arrow after a drag opened ${JSON.stringify(urls)}`)
})

await step('contacts: add via paste details', async () => {
  await page.goto(base + '/contacts', { waitUntil: 'networkidle' })
  await page.getByRole('button', { name: 'New contact' }).click()
  await page.getByRole('button', { name: 'Paste details' }).click()
  await page.getByLabel('Pasted details').fill('Thabo Timber\nTimber City (Pty) Ltd\nCell: 082 555 0199\nthabo@timbercity.co.za\nhttps://timbercity.co.za')
  await page.getByRole('button', { name: 'Pull out the details' }).click()
  await page.waitForTimeout(300)
  await shot('05a-paste')
  const name = await page.getByPlaceholder('Joe Mahlangu').inputValue()
  const company = await page.getByPlaceholder("Joe's Joinery").inputValue()
  const wa = await page.getByPlaceholder('27…').inputValue()
  if (name !== 'Thabo Timber' || company !== 'Timber City (Pty) Ltd' || wa !== '27825550199') throw new Error(`parsed badly: ${name} / ${company} / ${wa}`)
  await page.getByRole('button', { name: 'Add contact' }).click()
  await page.waitForTimeout(600)
  const c = await page.locator('text=Thabo Timber').count()
  if (!c) throw new Error('contact missing')
  await shot('05-contacts')
})

await step('site days: no-show today + blocker', async () => {
  await page.goto(base + '/projects', { waitUntil: 'networkidle' })
  await page.getByRole('link', { name: /Kitchen cabinet refresh/ }).first().click()
  await page.waitForTimeout(700)
  const card = await page.locator('text=Site days').count()
  if (!card) throw new Error('site days card missing')
  await page.getByRole('button', { name: 'No-show today' }).click()
  await page.waitForTimeout(700)
  await shot('05c-site-days')
  const row = await page.locator('text=Today').count()
  if (!row) throw new Error('no-show not logged')
  const line = await page.locator('text=Last: no-show').count()
  if (!line) throw new Error('header last-visit line missing')
  await page.getByRole('button', { name: 'More' }).click()
  await page.getByRole('menuitem', { name: 'Mark as blocked…' }).click()
  await page.waitForTimeout(400)
  await page.getByRole('button', { name: /^Parts/ }).click()
  await page.getByPlaceholder('Waiting for Chris to confirm Monday').fill('Hinges on back-order until the 20th')
  await page.getByRole('button', { name: 'Mark blocked' }).click()
  await page.waitForTimeout(600)
  await shot('05d-blocked')
  const chip = await page.locator('text=Blocked · Parts').count()
  if (!chip) throw new Error('blocker chip missing')
  await page.goto(base + '/', { waitUntil: 'networkidle' })
  await page.waitForTimeout(600)
  const first = await page.locator('a[href^="/projects/"]').filter({ hasText: 'Blocked · ' }).count()
  if (!first) throw new Error('blocked project not badged on the hub')
})

await step('quote expiry badge', async () => {
  await page.goto(base + '/projects', { waitUntil: 'networkidle' })
  await page.getByRole('link', { name: /Borehole pump replacement/ }).first().click()
  await page.waitForTimeout(600)
  await page.getByRole('tab', { name: /^Money/ }).click()
  await page.waitForTimeout(400)
  const expired = await page.locator('text=Expired').count()
  if (!expired) throw new Error('expired badge missing')
  await shot('05e-expired')
})

await step('hub: inbox shows a nudge from Kay', async () => {
  await page.goto(base + '/', { waitUntil: 'networkidle' })
  await page.waitForTimeout(600)
  const inbox = await page.locator('text=waiting for you').count()
  if (!inbox) throw new Error('inbox not shown')
  await shot('05b-inbox')
  await page.getByRole('button', { name: 'Got it' }).first().click()
  await page.waitForTimeout(400)
})

await step('complete project → celebration', async () => {
  await page.goto(base + '/projects', { waitUntil: 'networkidle' })
  await page.getByRole('link', { name: /Patio pergola/ }).first().click()
  await page.waitForTimeout(600)
  await page.getByRole('button', { name: 'More' }).click()
  await page.getByRole('menuitem', { name: 'Done' }).click()
  await page.waitForTimeout(1200)
  await shot('06-celebration')
  const c = await page.locator('text=Quest complete').count()
  if (!c) throw new Error('no celebration')
  await page.getByRole('button', { name: 'Onwards!' }).click()
})

await step('settings: theme toggle + rename', async () => {
  await page.goto(base + '/settings', { waitUntil: 'networkidle' })
  await page.getByRole('tab', { name: /Dark/ }).click()
  const theme = await page.evaluate(() => document.documentElement.getAttribute('data-theme'))
  if (theme !== 'dark') throw new Error('theme not applied')
  await page.getByRole('tab', { name: /Light/ }).click()
})

console.log(errors.length ? `\n${errors.length} errors:\n${errors.join('\n')}` : '\nNo console/page errors.')
await browser.close()
if (failed || errors.length) process.exit(1)
