import { chromium } from 'playwright'
const base = 'http://127.0.0.1:4173'
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' })
const context = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true })
await context.addInitScript(() => { localStorage.setItem('hub-demo-user', 'u-russel'); localStorage.setItem('hub-theme', 'light') })
const page = await context.newPage()
await page.goto(base + '/projects', { waitUntil: 'networkidle' })
await page.getByRole('link', { name: /Kitchen cabinet refresh/ }).first().click()
await page.waitForTimeout(600)
await page.getByRole('tab', { name: /^Board/ }).click()
await page.getByRole('button', { name: 'Open board' }).click()
await page.waitForURL(/\/board$/)
await page.waitForTimeout(800)
await page.getByRole('button', { name: 'Colour' }).click()
await page.waitForTimeout(400)
await page.getByPlaceholder('#7A8F6E').fill('#847562')
await page.waitForTimeout(400)
await page.screenshot({ path: 'qa-shots/flows/c1-colour-editor.png' })
const name = await page.getByPlaceholder('Dusty Sage').inputValue()
console.log('name for #847562:', name)
await page.getByPlaceholder('#7A8F6E').fill('#B3AB9F')
await page.waitForTimeout(300)
console.log('name for #B3AB9F:', await page.getByPlaceholder('Dusty Sage').inputValue())
await page.getByRole('button', { name: 'Pin it' }).click()
await page.waitForTimeout(600)
await page.getByRole('button', { name: 'Done' }).click()
await page.waitForTimeout(400)
await page.screenshot({ path: 'qa-shots/flows/c2-colour-pin.png' })
await browser.close()
